version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: osint-db
    environment:
      POSTGRES_USER: miska
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: osinthunt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - osint-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: osint-backend
    depends_on:
      - db
    environment:
      - DB_USERNAME=miska
      - DB_KEY=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=osinthunt
      - SECRET_KEY=dev-key-for-development-only
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    networks:
      - osint-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: osint-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    networks:
      - osint-network
    restart: unless-stopped

networks:
  osint-network:
    driver: bridge

volumes:
  postgres_data: